spring.application.name=SmartResumeBuilder

# Spring AI Ollama Configuration
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=llama3.2
spring.ai.ollama.chat.options.temperature=0.3

# File Upload Configuration
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Thymeleaf
spring.thymeleaf.cache=false

# MongoDB Configuration
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=cvision_resumes
spring.data.mongodb.auto-index-creation=true

spring.mvc.format.date=yyyy-MM
spring.jackson.date-format=yyyy-MM
spring.jackson.serialization.write-dates-as-timestamps=false